import { type AppType } from "next/app";
import { Inter } from "next/font/google";
import { api } from "~/utils/api";
import "~/styles/globals.css";
import Nav from "~/components/Nav";
import Head from "next/head";
import ShoppingBagProvider from "~/context/shoppingBagContext";
import ModalsProvider from "~/context/modalsContext";

const inter = Inter({ subsets: ["latin"] });

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <ModalsProvider>
      <ShoppingBagProvider>
        <>
          <Head>
            <title>E-commerce</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main
            className={`${inter.className}   min-h-[100dvh]  bg-gray-50 text-gray-800`}
          >
            <Nav />
            <section className="mx-auto min-h-[100dvh] max-w-[1600px] ">
              <Component {...pageProps} />
            </section>
          </main>
        </>
      </ShoppingBagProvider>
    </ModalsProvider>
  );
};

export default api.withTRPC(MyApp);
