import { type AppType } from "next/app";
import { Inter } from "next/font/google";
import { api } from "~/utils/api";
import "~/styles/globals.css";
import Nav from "~/components/Nav";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>E-commerce</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`${inter.className} flex min-h-screen flex-col items-center  bg-gradient-to-b from-slate-800 to-slate-900 text-white`}
      >
        <Nav />
        <Component {...pageProps} />
      </main>
    </>
  );
};

export default api.withTRPC(MyApp);
