import Head from "next/head";

import { api } from "~/utils/api";

export default function Home() {
  // const { data: products, isLoading:isGettingProducts } = api.product.getAll.useQuery();
  const { data: categories, isLoading: isGettingCategories } =
    api.category.getAll.useQuery();
  if (isGettingCategories) return <span>Loading...</span>;
  if (!categories) return <span>Something went wrong.</span>;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-slate-800 to-slate-900 text-white">
        {categories?.map((category) => (
          <div key={category.id}>
            <p>{category.name}</p>
          </div>
        ))}

        {/* {products?.map((product) => (
          <div key={product.id}>
            <h1>{product.name}</h1>
            <p>{product.price}</p>
          </div>
        ))} */}
      </main>
    </>
  );
}
