import Head from "next/head";
import Nav from "~/components/Nav";
import { api } from "~/utils/api";

export default function Home() {
  // const { data: products, isLoading:isGettingProducts } = api.product.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center  bg-gradient-to-b from-slate-800 to-slate-900 text-white">
        <Nav />

        {/* {products?.map((product) => (
          <div key={product.id}>
            <h1>{product.name}</h1>
            <p>{product.price}</p>
          </div>
        ))} */}
      </main>
    </>
  );
}
