import Head from "next/head";
import Nav from "./Nav";
import Footer from "./Footer";
import { PromosBanner } from "./PromosBanner";
import { bannerPromos } from "./promosData";

const Layout: React.FC<React.PropsWithChildren> = ({ children }) => {
  return (
    <>
      <Head>
        <title>e.fashion</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`bg-slate-50 font-body text-slate-800`}>
        <Nav />
        <PromosBanner promos={bannerPromos} />
        <section className="mx-auto min-h-[100dvh] max-w-[1600px] ">
          {children}
        </section>
        <Footer />
      </main>
    </>
  );
};

export default Layout;
